name: Michal Olender
title: Window Management Software
description: Window Management Software Overview
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: vistula

# logo: "/assets/images/Morris_badge.png"

aux_links:
  "Source repository on GitHub":
    - "//github.com/KomunikacjaTechnicznaVistula/michal-olender"

back_to_top: true
back_to_top_text: "Back to top!"

# footer_content: Here add something relevant